### ISSUE TITLE
Unable to follow getting started guide in CRA or Vite

### ISSUE THREAD

**Issue by tim-field** [remirror/remirror#1755] opened 2022-06-28 10:00 UTC
### Summary

Unable to follow getting started guide in CRA or Vite

### Steps to reproduce

Create a fresh CRA app or Vite project 

`yarn create vite client --template react-ts`

install per the tutorial

`yarn add remirror @remirror/react @remirror/pm`

Paste the flowing example in the getting started guide

https://remirror.io/docs/getting-started/render-editor

### Expected results

Expected to be able to follow along with tutorial.

### Actual results

<img width="908" alt="image" src="https://user-images.githubusercontent.com/1326910/176151893-1d6ea054-5e0a-4fd7-855d-4d730d288e7e.png">

Similar issue with Create React App ( where I'm also using Typescript )

Node v16, React 18

**Comment by ocavue** [comment] 2022-07-01 09:32
Here are some examples with CRA and Vite here: https://github.com/remirror/remirror-examples. Let me know if this helps.

**Comment by HeavenFox** [comment] 2022-08-08 03:36
This is caused by a bug (or maybe not a bug?) in `@remirror/pm` package, where it depends on `prosemirror-transform` < 1.5.0. That module is transpiled into ES5, and therefore other packages that transpile into ES6 classes are not compatible with this.
Upgrading `@remirror/pm` to the beta version would solve the issue.

**Comment by ocavue** [comment] 2022-09-20 11:11
This should be fixed with [remirror v2](https://remirror.io/blog/announcement-v2), so I'm going to close this issue. Let me know if someone still get this error.

**Closed by ocavue** 2022-09-20 11:11 UTC
Labels: type: bug :beetle:
