### ISSUE TITLE
usePositioner doesn't support multiple editor instances

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#834] opened 2020-12-21 22:25 UTC
### Summary

Using the `usePositioner` hook when multiple editors are mounted on the page does not take into account the provider context. For [example](https://github.com/goabstract/block-editor-test/blob/use-positioner-bug/src/App.js#L29), floating menus positioned this way are positioned on the incorrect editor.

### Steps to reproduce

- Repo: https://github.com/goabstract/block-editor-test/tree/use-positioner-bug
- `git checkout use-positioner-bug`
- `yarn install`
- `yarn start`
- Select text in both editors

### Expected results

- One menu shows up at a time based on which editor is in focus, menu from one editor is not affected by state or positioned on another

### Actual results

- Menus from both editors are overlaid

### Screenshot(s)

![Kapture 2020-12-21 at 14 24 59](https://user-images.githubusercontent.com/380914/102827966-672ca080-4398-11eb-9020-14a413767f97.gif)

**Comment by tommoor** [comment] 2021-01-04 21:44
@ifiokjr small ping on this one for categorization and sponsor label, it's quite blocking for us.

**Comment by ifiokjr** [comment] 2021-01-04 21:55
I've added a `clone()` method to the positioner since the problem is caused by shared instances of the positioner. I'll be merging the work I've don in the beta branch at some point tomorrow. It may take a few days after that before the first release.

**Comment by tommoor** [comment] 2021-01-13 18:29
Howdy, how's that beta release looking?

**Comment by shnraj** [comment] 2021-02-11 03:05
@ifiokjr @tommoor is there a workaround for this issue? We have multiple editors on the page but only one is "active" and needs the positioner. I tried conditionally rendering the component that needs the positioner but that didn't help.

**Comment by ifiokjr** [comment] 2021-02-11 08:51
I'll do a hot fix later today. It's fixed in the tag `pr706` but there's also a few other breaking changes.

**Comment by ifiokjr** [comment] 2021-02-20 05:58
Some context as to why this is an issue. The positioners are being exported as singletons and each positioner holds the state within the instance. 

In order to mitigate this issue there is actually a workaround as follows. 

```ts
import { Positioner, cursorPopupPositioner } from '@remirror/extension-positioner';
import { usePositioner } from '@remirror/react-hooks';

function useMyPositioner() {
  return usePositioner(Positioner.fromPositioner(cursorPopupPositioner, {}));
}
```

This will prevent this issue with the singleton being reused across editors. 

Hopefully, this solves the short-term issue. 

Long term I encourage you to upgrade to the beta version since the Positioners are vastly improved.

**Comment by ifiokjr** [comment] 2021-02-20 05:58
@tommoor @shnraj I'm closing this for now since there is a temporary workaround.

**Closed by ifiokjr** 2021-02-20 05:58 UTC
Labels: status: confirmed :green_circle:, status: sponsored :sparkling_heart:, type: bug :beetle:

**Comment by tommoor** [comment] 2021-03-01 18:37
> Long term I encourage you to upgrade to the beta version since the Positioners are vastly improved.

Any word on when a release of that might be? Sidenote: I've referred several folks to remirror in the last month but more than once they have come away terribly confused because of the mix of `main` / `beta` / `next` branches.
