### ISSUE TITLE
Some dependencies are obsolete

### ISSUE THREAD

**Issue by hungtcs** [remirror/remirror#2279] opened 2024-07-29 03:10 UTC
### Summary

For start a new project, it is wise to choose the latest version of dependency packages, 
like prettier or styled-components etc...

However, after adding remirror, there is a version compatibility problem 
because some of remirror's dependencies are out of date.

### Expected results

remirror should have good compatibility.

### Actual results

```
├─┬ @remirror/react 2.0.35
│ └─┬ @remirror/extension-react-tables 2.2.19
│   └─┬ @remirror/react-components 2.1.17
│     └─┬ @remirror/extension-code-block 2.0.18
│       └── ✕ unmet peer prettier@^2.8.8: found 3.2.5
├─┬ remirror 2.0.39
│ └── ✕ unmet peer prettier@^2.8.8: found 3.2.5
├─┬ @remirror/styles 2.0.7
│ └── ✕ unmet peer styled-components@^5.3.10: found 6.1.1
```

### Possible Solution

Update dependencies to latest version and reasonable configuration compatibility flags.

**Comment by mdmower** [comment] 2024-07-30 01:44
Looks mostly like a duplicate of https://github.com/remirror/remirror/issues/2250 except for `styled-components`.

**Comment by hungtcs** [comment] 2024-07-30 01:50
Yeah, it's the same problem. 

Perhaps there could be broader compatibility for styled-components, e.g. `"styled-components":">=5.3"`

https://github.com/remirror/remirror/blob/a0cc38df84d3de7d3fd72ae1804803bf4b76b0de/packages/remirror__styles/package.json#L64

**Closed** 2024-07-30 15:33 UTC
Labels: type: bug :beetle:
