### ISSUE TITLE
Bug in which bold and italic fonts overlap when writing in markdown syntax

### ISSUE THREAD

**Issue by saseungmin** [remirror/remirror#1523] opened 2022-02-20 09:16 UTC
### Summary
When using 'Bold Extension' and 'Italic Extension' as the markdown syntax, the two extensions overlap and can't be written.

With throw "Uncaught RangeError: Position <number> out of range" Error
### Screenshot(s)

https://user-images.githubusercontent.com/60910665/154835990-6e38cd2c-3a7d-40f9-9c74-00abd8e040fe.mov

**Comment by whawker** [comment] 2022-05-28 09:38
I believe this was fixed by https://github.com/remirror/remirror/pull/1598, I cannot reproduce this anymore

**Closed by whawker** 2022-05-28 09:38 UTC
Labels: type: bug :beetle:
