### ISSUE TITLE
Extending menus in Wysiwyg

### ISSUE THREAD

**Issue by marek-baranowski** [remirror/remirror#178] opened 2019-11-24 22:06 UTC
Hi,

Once again many thanks for the recent [PR](https://github.com/ifiokjr/remirror/pull/176) regarding additional prop for extensions in Wysiwyg.

I'm trying now to add relevant buttons regarding my extension to both menus. Is that possible the easy way? :)

One more thing, I have not yet managed to fully investigate the problem but it seems like there is an issue with my native Prosemirror plugin being wrapped with `NodeExtension`; I believe there is a duplication of some attributes like `state` or `key`. It would be great if native ProseMirror plugins could work seamlessly, without wrapping. Nevertheless when I find what is the exact problem I will let you know.

Best!

**Comment by ifiokjr** [comment] 2019-11-25 08:00
In short, extending menus for the built in editor is not a built in feature right now, but it needs to be. 

I'll look into how best to add this functionality.

> I believe there is a duplication of some attributes like state or key

I'm not sure what you mean by this?

**Comment by zhaoyao91** [comment] 2020-02-12 02:55
vote for customizing the wysiwyg:

- customize extensions (add/remove)
- customize menu items (add/remove)
- customize theme/styles
- guide for concepts and how-to

**Comment by ifiokjr** [comment] 2020-07-02 05:20
I'm currently addressing these issues in #320 .

**Comment by ifiokjr** [comment] 2020-08-11 20:38
Closing as a duplicate of #452 and #453.

**Closed by ifiokjr** 2020-08-11 20:38 UTC
Labels: status: duplicate
