### ISSUE TITLE
active.heading({ level }) should return the active state of the specific heading level

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#379] opened 2020-07-24 19:08 UTC
## Description

We'd ideally should be able to check a heading's active state by doing something like:

```
const h1Active = active.heading({ level: 1 })
const h2Active = active.heading({ level: 2 })
```

Currently, it seems as if we can only check whether _any_ header is active by using `active.heading()`.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment] 2020-07-25 03:54
**[Playground Link](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDClsuQDKuVrnLCxE6SAVncuvqGOAREAEKYzPwAogAe7rykKJi8nuKYkjIKtPQ4KuTx5InJvCoARpH8gQYYIVYAkq7MKAhxCUkpad5ZirmqBe0lKihNLdXBxkQAqgLk2M285G1FHaki6Zm+vcr5hcUpKnz8cwvk47WT+AAS5Kz8KLycy-trXhk+2Up5AytDABa3e6Pc5GUL4AAyKFIuEYCgoBHW3S2OR26Dh5FwKma0JBdSI1BRTAYADcUMdsA4KABZVi8VicOaUqjbHBMxiYJK4EpzLrvHqE1R+czVBApaH4aIADQAKtEAHJOeoAeQV+AAvPgANr6fD4RYAd2ugIeTz2qwAFABKWA6vXkQ0RKLPC3W20G-CNVjNVpmkpWm2pO2Gmbk07Ov2uwPuyHQ2HkeH+-QAXT0vH0oj45hK+CpRWIVsItt1KhU+GlAJIFHwWE53Ow+D+mEwAGt8F7mJh9aQxDh8LhsGZmya+xWEMR6EUCBRmOQs50HiOPOR7rgcAA6Iv4UWJUIVXCrsCWGeiCz4BSiEQaxzs2spObmgDkZWIZTKM4fltTm+34qIorAYC0vwpCWP4KDEh4l6VsyArmkQrDEKuUzoPwbjkJAfbYMQkGfvom4KLg46pOam66gAPPcxJnuQohqsA54iNC7AznRRB7geR40aeNYjCUGEPqwZSkJEiHkA+lhCEIAB8pG6vgZHPvuKSyXJ+ApLY3rNnRBZqlJW4ZIBAikGuq6cJwM6OvwVpCCpclMSxwBEKIKS4AA6uQKCcH8uAYWBEFrhUUQFgA-PgT6VA++AYUcNEPMuwg2YGqm6jJSXJbqYS2WR5SIauvCpel5GKXltm6upmnaZa6p6f+hnASZmBmTOnretZpX4PZ5CsT2vBuR5Xk+W2Wb+SMXotCFYWBfwkXRbMohxYIkm2QVhW6vUWU5Up+VZcVylpel5UtFpwA6TVBlAcZpnmeQIYnHFbX7clnXdc5vXuZ53m+cN5BrjF8z3VVoXhVEM0kHNC0Jct7VTBtu3bY9RW5Xtq1lbwGlHZV1X6QBF0NU15A3HcJpwfgM4QcwGHQMIlqJSjHW4MxXWOT1fUfYNfk-QCROPCTZPkBT+BU0IgOTRFUVg8c82LIttOFStq1XNAsNI-Dq0KSr7WHQgx2ndjdWXY112E0CnC8+Q5MYQATNTsurc9zOvazA1fVy-lcybZsW-g1vC-gQNTaDMVS-FS0I-g8uFVclvK1tEfkSolER7hgaJXhpQAFTpzq6dln8ULY1giy9fpvWsA83a4BWy4jL2QFtrw7B9k2zBlKw2CkCoCB-BIHgjNRACOxB0PGG6pOnKj6D+BBOIBzDMNEK44BhdjqvguvALaU9WAyuCUE2MIMOgIF6xdnhXhQBJfNgVqprqBFEWvm4UeBcfyZRhBrp-O975gB+YEf1l8AqFfmRXMvBiBAIjtlROtpk5CFTFvGe7YF412wK5Ac6B0A8g1OvTeYoCA-BeDSOkDJ6zn3IMQ+k94pSygVMqBUyddRbyIMSL02FLDqT+LSBkZ9oKXz6CwDg3BMBHHNIQ1YlDSGfiAaWAAIvzDEHhK751OLae+2BiJP34coWEmBSTklkoZKh2A6LiJKJIuYts5KsOYNhOiNjsJWNRrYLhjwmacO4eQKxICkFzxQaueswCn4qG0USPRZI5grTgV+RYsRQT4ElghZg09Z7z0XmgjBWDsA6BAEIIAA)**

I'm unable to reproduce a broken example (see playground link above). It may have inadvertently been fixed in a recent version. See #372

Try installing `remirror@1.0.0-next.9` and let me know if you're still facing issues.

![2020-07-25 04 51 13](https://user-images.githubusercontent.com/1160934/88448160-8dbecd80-ce32-11ea-9d47-f645e98f1b44.gif)

**Closed** 2020-07-25 05:48 UTC
