### ISSUE TITLE
ReactComponent extensions do not work in next branch

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#336] opened 2020-07-15 00:29 UTC
## Description

I have created a minimal reproduction repo to show the problem here, https://github.com/tommoor/remirror-custom-blocks

Essentially, adding a custom ReactComponent block to the mix immediately throws prosemirror errors. If I add a `debugger` statement in the render method for the custom block it is never triggered, the custom block does seem to end up in the list of NodeViews provided to pm though.

Perhaps this is just due to `@next` being in development, or perhaps the API changed subtly and hasn't yet been documented?

## To reproduce

- clone the repo ^
- yarn install
- yarn start
- Hit "Toggle custom block"

You'll see something like:
![image](https://user-images.githubusercontent.com/380914/87489331-9ecc3b00-c5f7-11ea-9fcd-0c6cc5cc6e50.png)

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment] 2020-07-15 15:24
Good spot. It's actually odd since the package shouldn't even have been published yet. I need to look at how the release pipeline is publishing packages too early. 

Anyway, thanks for flagging this as an issue and providing a thorough reproduction of the issue. 

I'll be addressing the problem in #320.

**Comment by tommoor** [comment] 2020-07-15 15:39
No problem! I'm evaluating remirror for an internal project, but the current churn makes it hard to jump on board at this time. Do you have an idea of what's causing this? Perhaps I could patch in the meantime.

**Comment by ocavue** [comment] 2020-07-16 07:54
> I need to look at how the release pipeline is publishing packages too early.

Maybe because I merged Changeset's PR? 😅

**Comment by ifiokjr** [comment] 2020-07-16 17:09
> Maybe because I merged Changeset's PR? 😅

I think this one is on me actually on me by adding the release via `pnpm`. I'm not too sure how to workaround it in the short term.

https://github.com/remirror/remirror/blob/a4c90e7f7976a18aaf69bb6d5a9c84d4354b25d8/.github/workflows/ci.yml#L425-L429

**Comment by ocavue** [comment] 2020-07-16 17:46
> how to workaround it in the short term

add `private: true` in `package.json`?

**Comment by ifiokjr** [comment] 2020-07-17 12:25
@tommoor I've managed to replicate this by pasting the following into the [playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBIqfO3MDExecl5cAFEAD1xQ0hRgh3FA5wVaehwVcmjY+N4VV3MAWgRArBCwjwMg419FdOxGBgA3FH5ybEsycgBZVl5WTnbOimo05USnGVSlDIL3ED0qox98ADlMNqiY3jjgy3W2gHEedEsS3ib23ACwMD7BESTJKbrlFRKFSq8a-ApcACFmJgEABrAAq7HQ5AmyRk8leGXQYHegTuAlIlX0CDYpFI+FsZFwgUBwJBWxyCSy234eIO5HJO1yhH0+HwCFcMTpAGUoQgABRU7CsACUzN4rNZClwxGw4uALIlrNYuFw2FIkDFisVADpdYLWNq2qJWMRmLhSHzhbAFVq2YTAhqiEaTWaNTIEPawDJhDaJUJreKtedtrg3aheMwUCEAFQyAO27iYYjoDV045J9Dakmg+NaokAEQA8t0NbwNtCALwAPnwAG0ZP0mnH8PrDYE+WW2lb8AAGAC6vqEi1ZQn0CvZ5GV5BuaJpls1EqlMrlvtZRM4nGY0892ZBGvn1bZwUueBn9z5f13EKhfNwAAsUKRtbhIeRLMAhMLhYPhz7eArBgIfowHIecF0VJdZXwAByD1SCJMBoN-Ud-0DPxrlKYJQgICt8D5IhOzfMQcAAd1YbB+GoURhFFQ95UDSVyGlKCAB50EIXVtUI7VlVVUgRAUUQK2AURSPIyjyFEEQVCrRZfRUFR8Eg8U+XkxTWRY-gUCaI8wmw8ItNwVgACMt2E41mAoATJPMsSKKooQqzUrUAElODLBRdJDZyNJULSmichj8AU-BhWQxYULHXhzng-BwgADTBcJVi5FzCxS-BcNrEISJMSd-Ew8oImyRlgktSwcvxHcgVBBldl4S0+zkvJo1jcVo3wMEHzxEogiKrzWCjPF72hchDJwfB7km3h2HwIlMGYYzyNId47wkaEUAIBQAEdiDocgnxZaMVCxYJYq5O5mGYAzNpwDU7EyvDaJrejWRilZAMoTBMFwRpMHQUgzlRe48REXCulGGZsEtZrGOYlTfU07TAttFjjOIFUEmCWxI1BYSDxrXrZyfddN23eDiRqkFLUcuCEJYlR0cx3gUa1JGdOATjPu+36GABmngtZ3z-NZsL9CHKL3vwC7WCum6iWwAB1IV0ChbBHoJhcpapCleF6fpBnV8GKH1gZ2j5BKkpStKUrF1C3rOlYmll4giOxu8+kGBxjaoBEGg0RM+H4AUSvq03DbC4LFPzcgtxiObuvwSMQiiuHlzwxHIfqP6WjabBV3wNEzewYSddKvW+mLlDbWd5hXeE2vXerrV3c98hhNb3hBmb1khYlFiZbl8b1ZkxGVCz5Qc9adpRYi5qsmWfBnVNAhB+u4fldYVX2kWEAhCAA).

```json
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "asdf"
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "asdf"
          }
        ]
      },
      {
        "type": "custom",
        "attrs": {
          "custom": "custom"
        },
        "content": [
          {
            "type": "text",
            "text": "asdf"
          }
        ]
      }
    ]
  },
  "playground": {
    "m": 1,
    "c": "import { useRemirrorPlayground } from \"@remirror/playground\";\nimport React, { FC } from \"react\";\nimport { ReactComponentExtension } from \"remirror/extension/react-component\";\nimport { RemirrorProvider, useManager, useRemirror } from \"remirror/react\";\nimport { NodeExtension, NodeGroup, convertCommand } from \"remirror/core\";\nimport { setBlockType } from \"@remirror/pm/commands\";\n\nclass CustomBlockExtension extends NodeExtension {\n  createNodeSpec(extra) {\n    return {\n      attrs: {\n        ...extra.defaults(),\n        custom: { default: \"custom\" }\n      },\n      content: \"inline*\",\n      group: NodeGroup.Block,\n      toDOM: node => [\"nav\", extra.dom(node), 0]\n    };\n  }\n\n  createCommands() {\n    return {\n      toggleCustomBlock: () => convertCommand(setBlockType(this.type, {}))\n    };\n  }\n\n  get name()  {\n      return 'custom';\n  }\n\n  ReactComponent = ({ node, forwardRef }) => {\n    return <p {...node.attrs} ref={forwardRef} />;\n\n    // return (\n    //   <div contentEditable={false} ref={forwardRef}>\n    //     Ignore content\n    //   </div>\n    // );\n  };\n}\n\n\nconst EXTENSIONS = [new ReactComponentExtension(), new CustomBlockExtension()];\n\n/**\n * This component contains the editor and any toolbars/chrome it requires.\n */\nconst SmallEditor: FC = () => {\n  const { getRootProps, commands } = useRemirror();\n\n  return (\n    <div>\n      <button onClick={() => commands.toggleCustomBlock()}>custom</button>\n      <div {...getRootProps()} />\n    </div>\n  );\n};\n\nconst SmallEditorWrapper = () => {\n  const extensionManager = useManager(EXTENSIONS);\n\n  const { value, onChange } = useRemirrorPlayground(extensionManager); // Delete this line\n\n  return (\n    <RemirrorProvider\n      manager={extensionManager}\n      value={value}\n      onChange={onChange}\n    >\n      <SmallEditor />\n    </RemirrorProvider>\n  );\n};\n\nexport default SmallEditorWrapper;\n"
  }
}
```

**Comment by ifiokjr** [comment] 2020-07-17 15:28
So I've fixed the initial issue, but another issue has cropped up in it's place. When you delete a custom node view with content the same issue crops up for the same reason.

**Comment by tommoor** [comment] 2020-07-20 21:18
I think It's fair to count this as fixed now 👍

**Comment by ifiokjr** [comment] 2020-07-21 11:35
I think I'll leave it open till I've documented how to get do it. 

I also want to take a look at inline content again later this week.

**Comment by ifiokjr** [comment] 2020-07-26 17:40
**[Playground Link](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBIqfO3MDExecl5cAFEAD1xQ0hRgh3FA5wVaehwVcmjY+N4VV3MAWgRArBCwjwMg419FdOxGBgA3FH5ybEsycgBZVl5WTnbOimo05USnGVSlDIL3ED0qox98ADlMNqiY3jjgy3W2gHEedEsS3ib23ACwMD7BESTJKbrlFRKFSq8a-ApcACFmJgEABrAAq7HQ5AmyRk8leGXQYHegTuAlIlX0CDYpFI+FsZFwgUBwJBWxyCSy234eIO5HJO1yhH0+HwCFcMTpAGUoQgABRU7CsACUzN4rNZClwxGw4uALIlrNYuFw2FIkDFisVADpdYLWNq2qJWMRmLhSHzhbAFVq2YTAhqiEaTWaNTIEPawDJhDaJUJreKtcqHfhVcRyAHbQAjIGgjVhiO+1ncTDEdAaunHVPobUk0GRrXnba4DW8U3MAuKokAEQA8t1SxtoQBeAB8zlI6D6Ml9QkWrKE+gV7PIyvINzRNMtmolUplcqT+BQOyuBNIRLAeZBGr5HvXgVFbfwfKIqss-BQneVCAAFsJD+35YHbRer7hbwB+bV81Xa5cUPAf2wbUKGYchzFybUnksXAb0vbVcEhchtRHMdLWFYV+1tfA51lUNsHDLDFX9XssMHXgFUGAh+jAchpxnRVcPFAByPcN2Ysih0DPxrlKYJQgIZtjyIXgm0sUQcAAd1YbB+GoUR73wI8n0Y8hpTwvlFwAHgvJo2WCYtwgvXBWBjchm2AY1mAoER13YMCLKIEogWwDVmMkuCYmYywozMEEUz4fgAhctyY3Dbz8BvcgUE4G8S3waAAAZEssSTWlgtyksSgBSCKhCEVtF1ZYBRLabVlVVUgUM9cjbS0lRdMK598EwhU+30ciuPOdd8HCAANMFwlWLkAEla2GpT8AAbRCSSTFHfw+PKCJskZYJLUsWb8U9LcGV2XhLQAXUWfQVAAKjOlkzvwME4LxEogmW-SwlYf9Qyi-ByGMnB8HuX7eHYUNMEwZhfLVd4bwkaEUAIBQAEdiDocgqqulQsWCHquTuZhmCMmGcA1OxJunZThwxlYqMoYHcEaTB0FIM5UXuPERCErpRhmbBLROwMmOPX0dJQJomrqqNiBVBJglsZgUFBCySfbB7Jyq-9Vx22MQUtAqAEF+EENcN3wLd6rFiXeBFrVBb04BdW1Snqdp+mtfwFQLdZerGoVVreHaijeG6ggsdYHG8aJbAAHUhXQKFsGJh8ZwDz7Vv23p+kGWO2YoVOBnaPl+sG4axuG72yZ2FYmmD8NLClm8+kGBxM6oBEGg0AKBAFZPcmz9PMJdlR8GrcgwJid7L3wGWQi4yU1Pnfnmq0jn6lplo2mwRc0Rz7ALKpCleG79paq1CvmHDCzj-DQ-FRruvzOAa-eEGS-8DdiUtKDkPvtj12BZURflGX1o7QLbe19voLIyx8DOlNIHbGuNP6R1YNHdoiwQBCCAA)**

The link above is for a working playground showcasing the `ReactComponent` being rendered inside the editor. It doesn't yet support nodes with inline content and I'll address this in a new issue to be created shortly.

**Closed by ifiokjr** 2020-07-26 17:40 UTC
Labels: bug
