### ISSUE TITLE
`prosemirror.css` is not injected.

### ISSUE THREAD

**Issue by zhaoyao91** [remirror/remirror#228] opened 2020-02-13 05:40 UTC
## Description

I got the warning in the browser console: `ProseMirror expects the CSS white-space property to be set, preferably to 'pre-wrap'. It is recommended to load style/prosemirror.css from the prosemirror-view package.`

The prosemirror doc says we **SHOULD** include the css file: https://prosemirror.net/docs/ref/#view

But as the remirror is a css-in-js project, the css may be ported as some js content and injected at some point.

## Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by ifiokjr** [comment] 2020-02-19 13:03
I can't replicate on the docs editor https://docs.remirror.org/showcase/social/. 

Can you provide your setup?

**Comment by zhaoyao91** [comment] 2020-02-19 16:38
strangely, I removed my css injection, this time it does not show the warning. 
BUT, I did notice some lost style:

![Kapture 2020-02-20 at 0 36 07](https://user-images.githubusercontent.com/3808838/74853590-19f73100-5379-11ea-8ad6-f4f701b01997.gif)

![Kapture 2020-02-20 at 0 35 10](https://user-images.githubusercontent.com/3808838/74853412-def4fd80-5378-11ea-87ba-29a9ba8710e1.gif)

- the first gif shows the correct style with prosemirror css, the selected node has outline;
- the second gif shows the wrong style without prosemirror css, the selected node does not has outline.

**Comment by ifiokjr** [comment] 2020-02-21 10:27
That was intentional, I had removed the outlined by setting the styling to `outline: 'none'` in several places within the codebase. However, I can see that without alternatives, that could be an accessibility issue. I'm happy to merge a PR which reverts this change.

I'll close this issue for now since the initial bug raised isn't reproducible.

**Closed by ifiokjr** 2020-02-21 10:27 UTC
Labels: needs information

**Comment by zhaoyao91** [comment] 2020-02-21 11:28
The prosemirror css is below, leave it here so you can have a glance and check if all their concerns have been covered by remirror:

```
.ProseMirror {
    position: relative;
  }

  .ProseMirror {
    word-wrap: break-word;
    white-space: pre-wrap;
    white-space: break-spaces;
    -webkit-font-variant-ligatures: none;
    font-variant-ligatures: none;
    font-feature-settings: "liga" 0; /* the above doesn't seem to work in Edge */
  }

  .ProseMirror pre {
    white-space: pre-wrap;
  }

  .ProseMirror li {
    position: relative;
  }

  .ProseMirror-hideselection *::selection {
    background: transparent;
  }
  .ProseMirror-hideselection *::-moz-selection {
    background: transparent;
  }
  .ProseMirror-hideselection {
    caret-color: transparent;
  }

  .ProseMirror-selectednode {
    outline: 2px solid #8cf;
  }

  /* Make sure li selections wrap around markers */

  li.ProseMirror-selectednode {
    outline: none;
  }

  li.ProseMirror-selectednode:after {
    content: "";
    position: absolute;
    left: -32px;
    right: -2px;
    top: -2px;
    bottom: -2px;
    border: 2px solid #8cf;
    pointer-events: none;
  }
```

**Comment by ifiokjr** [comment] 2020-02-21 13:06
Here's the equivalent in the remirror codebase. 

https://github.com/remirror/remirror/blob/b096ed1dd300d682e28f9a7721ad9debbe1c1eb3/%40remirror/ui/src/ui-theme.ts#L244-L261

I think it's missing `font-variant-ligatures: none;` and `font-feature-settings: "liga" 0;` which may not have been a part of the `prosemirror.css` the last time I checked. 

Feel free to open a PR to add. It's probably there for a reason 😄

**Comment by zhaoyao91** [comment] 2020-02-21 18:53
I'd suggest introducing the prosemirror css content as it is somewhere and make additional stylings based on it. Since remirror is conceptually based on prosemirror, this way could keep it to be integral.
